### ISSUE TITLE
encoding errors

### ISSUE THREAD

**Issue by srid** [srid/readability#4]
```
bin/readability  -b http://www.nytimes.com/2010/09/07/health/views/07mind.html
Traceback (most recent call last):
  File "bin/readability", line 14, in <module>
    readability.main()
  File "/Users/sridharr/code/readability/src/readability.py", line 185, in main
    readable_html = readable(url)
  File "/Users/sridharr/code/readability/src/readability.py", line 165, in readable
    {content}'''.format(title=title, content=content)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 6744: ordinal not in range(128)
```

**Comment by srid** [comment]
use latin-1 encoding by default; closed by c68dbe9899ef92b27eb0281543bf2a3b676de095
